esphome:
  name: blesensor
  platform: ESP32
  board: m5stack-core-esp32

wifi:
  ssid: "oakridge"
  password: "donkeykong"
  domain: .home

logger:
  level: info

api:
  password: !secret api_password

ota:
  password: !secret ota_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
